### ISSUE TITLE
The API Gateway must include a discovery service

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/api_gateway#5]
The Discovery Service is an HTTP service ( aiomisc and AIOHTTP ).

**Config**:

the discovery service must get configuration parametwr from the config file:

the parameters are:

* ip
* port

**Way of working**

the discovery service must receive call from the microservice:

1. /subscribe
2. /unsubscribe
3. /discover

**Subscribe**:

the microservice send a POST to the subscribe url with:

* ip/host microservice
* port of the rest service of the microservice
* name of the microservice

**Unsubscribe**

the unsubscribe receive a POST with the following information:

* name of the service

**Discover**

the discover route must accept a GET with the following parameters:

* name of the microservice

the discover must check if the name exist and return the Host/port of the microservice

**Comment by vladyslav-fenchak** [comment]
Move to separate package "discovery"
